### ISSUE TITLE
Add new test case

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/MatrixAlgorithms#1]
Add a new test case for "getValue" function.

**Comment by Procoder16** [comment]
@TomaszWychocki Sir, I would like to work on this ticket.

Can you please assign me this project.

**Comment by Mayank662** [comment]
Hi @TomaszWychocki Hi would like to work on this issue.

**Comment by TomaszWychocki** [comment]
@AKKmath, I can't accept your PR. @Mayank662 was the first person asking to work on this issue - @Mayank662 of course please work on it. Don't forget to implement new test caseses in separate function ("TEST_002_...).

**Comment by AKKamath** [comment]
Of course. I didn't notice when I submitted the pull request. I apologize.

**Comment by TomaszWychocki** [comment]
No problem

**Comment by TomaszWychocki** [comment]
@Mayank662 are you still working on it?
