### ISSUE TITLE
Implement matrix concatenation method

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/MatrixAlgorithms#14]
Implement a new method, which concatenates 2 matices. It should be possible to concatenate 2 matices form the top, bottom, left and right:
![](https://i.imgur.com/gUx57tt.png)
It should be not possible (method should throw an exception) to concatenate 2 matrices in the following cases:
![](https://i.imgur.com/XYWaEkG.png)

Test function, test cases and method declaration are already in the code, just uncomment them and finish by adding your implementation.

**Comment by yarinvasket** [comment]
Can you assign this to me?
