### ISSUE TITLE
Implement matrix subtraction

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/MatrixAlgorithms#4]
Implement matrix subtraction using operator overloading.
New method sould return a new matrix as a result of subtraction: M = M1 - M2
It must be possible to make a chained subtraction operation: M = M1 - M2 - M3 - M4 - ...
This method should throw an exception if dimensions of M1 and M2 are not equal.

**Comment by MathurAditya724** [comment]
Hey, I would like to do this. Can you assign this to me? 😄

**Comment by TomaszWychocki** [comment]
Sure, you're assigned

**Comment by thecarooline** [comment]
Hi! Can you assign this to me?
