### ISSUE TITLE
Implement matrix multiplication

### ISSUE THREAD

**Issue by TomaszWychocki** [TomaszWychocki/MatrixAlgorithms#8]
Implement matrix multiplication using operator overloading:
- New method (operator*) should return a new matrix as a result of multiplication: M = M1 * M2
- Second method (operator*=) should modify current matrix as a result of multiplication: M1 *= M2
- These methods should throw an exception if dimensions of M1 and M2 are not correct.
- Remember: M1 * M2 != M2 * M1
- Test your code by adding new test cases.

**Comment by varuntumbe** [comment]
hey i can do this. please assign this to me .
Thanks in advance

**Comment by varuntumbe** [comment]
i did both of them but i didnt understand where exactly i should add my code.
little help please ..
Thank You.

**Comment by TomaszWychocki** [comment]
Please follow this tutorial:
https://www.youtube.com/watch?v=MnCfVxSw3ak

**Comment by varuntumbe** [comment]
@TomaszWychocki  sir i know how to make a pull request but i didnt get where to add my code in the repo.

**Comment by TomaszWychocki** [comment]
Add new methods in MatrixAlgorithms/Matrix2d.h and MatrixAlgorithms/Matrix2d.cpp
Create new test cases in MatrixAlgorithms/MatrixAlgorithms.cpp

**Comment by varuntumbe** [comment]
Hey i have successfully implemented and tested first overloading of multiplication. but for the second one i need o modify rows and cols data member which is defined to be const. should i remove const ? or any other workaround ?
Thanks in advance.

**Comment by TomaszWychocki** [comment]
Yeah, better remove const

**Comment by varuntumbe** [comment]
hey thanks ! i was struggling to merge.
